### ISSUE TITLE
Templatize tip of the week context note

### ISSUE THREAD

**Issue by d33bs** [CU-DBMI/set-website#13]
Each tip of the week blog post has included a contextual note near the top of content which includes repeated content ("Each week we seek to provide a software tip of the week geared towards helping you achieve your software goals..."). This issue outlines the possibility to templatize or reference this content from a single location, enabling one to quickly and uniformly address revisions for that content if needed.

**Comment by vincerubinetti** [comment]
You can put this in `_includes` in a file like `totw-note.html` or something, then include it in each post like `{% include totw-note.html %}`.

**Comment by d33bs** [comment]
Closing this with the merge of #22 and #23 which added and implemented content within `_includes` as suggested (thanks @vincerubinetti !).
